### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by Cozy-1** [xiangsanliu/Rules#1]
哥，您好，是这样的，因为我试了很多次都不行，所以能请问一下您联系方式教一下我吗？感谢🙏

**Comment by skylark36** [comment]
哪一步出错了？

**Comment by Cozy-1** [comment]
第一步就出错了，conf配置文件不知道怎么导入，节点也一直超时

**Comment by skylark36** [comment]
> 第一步就出错了，conf配置文件不知道怎么导入，节点也一直超时

我更新了readme，你看看设置节点的教程。

**Comment by Cozy-1** [comment]
好的，谢谢

**Comment by Cozy-1** [comment]
感谢，规则可用了，不过老哥方便您节点给我用下吗

**Comment by skylark36** [comment]
我的给你用不了，我内网用的
