### ISSUE TITLE
设置解锁节点

### ISSUE THREAD

**Issue by lovecll991224** [xiangsanliu/Rules#2]
作者您好 我是程序小白 想请问一下您解锁节点意思是那个节点本身就是已经解锁好的 还是说任意节点经过设置之后都可以成为解锁节点

**Comment by skylark36** [comment]
解锁节点的搭建参考 [nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)
这只是个代理规则，不包含任何解锁功能
