### ISSUE TITLE
大佬 小火箭 貌似没有IP-CIDR6 只有IP-CIDR 电报规则需要改下

### ISSUE THREAD

**Issue by luoluodaduan** [xiangsanliu/Rules#3]

**Comment by skylark36** [comment]
你用的哪个规则？merge-h2y.conf和merge-lhie1.conf是合并的上游大佬的规则，我不是很清楚。

gfw-ad-netease.conf 里面是有IP-CIDR6的telegram规则的。

> 另外，我是纯小白，不是大佬（不是谦虚😂）

**Comment by luoluodaduan** [comment]
https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/telegramcidr.txt

哈哈 github 人人大佬   这个网址 surge 有IP-CIDR6  小火箭只有 IP-CIDR

**Comment by skylark36** [comment]
哦哦，我现在懂你意思了，哈哈哈，我一会儿改一下😂

**Comment by luoluodaduan** [comment]
https://raw.githubusercontent.com/Loyalsoldier/geoip/master/data/telegram
这个是纯网址的

**Comment by luoluodaduan** [comment]
大佬辛苦  使用起来很爽  感谢大佬 用起来很爽

**Comment by skylark36** [comment]
已经修改了，非常感谢你的issue，同时感谢你的肯定。

**Comment by luoluodaduan** [comment]
IP-CIDR,149.154.160.0/20,PROXY,no-resolve
IP-CIDR,2001:b28:f23d::/48,PROXY,no-resolve
大佬是这样的  小火箭支持ipv6 但是格式是这样

**Comment by luoluodaduan** [comment]
大佬威武 ！！！！

**Comment by skylark36** [comment]
哎呀，这整的，非常感谢哈。
