### ISSUE TITLE
小火箭的优先级

### ISSUE THREAD

**Issue by luoluodaduan** [xiangsanliu/Rules#4]
大佬 小火箭的优先级 问题  貌似 下面的优先级更高 
https://github.com/blackmatrix7/ios_rule_script/issues/177
貌似应该把广告 放在代理或者直连下面 如有相同规则 广告就失效了

**Comment by skylark36** [comment]
是这样的吗，我还以为是最先匹配原则呢。
稍等，我验证一下。

**Comment by skylark36** [comment]
是的，经过简单的验证，这个issue没说错，是从头匹配到尾，以最后匹配到的为准。
