### ISSUE TITLE
大佬 有两个建议

### ISSUE THREAD

**Issue by luoluodaduan** [xiangsanliu/Rules#5]
一 是 电报的ip地址 貌似不对
https://core.telegram.org/resources/cidr.txt
应该是正确的
但是 ip地址 后面有空格和波折号 telegram_file.write('IP-CIDR,%s,PROXY,no-resolve\n' % line.replace('	', '').replace(' ', ''))
我不会编程只能用这个办法 
二是 cdn.jsdelivr.net 是有延迟的 貌似会延迟12小时以上 我推荐 还是用raw.githubusercontent.com 原来的比较好
def get_ad(url):
    res = requests.get(url)
    if res.status_code != 200:
        raise Exception('Connect error')
    return res.text.split('\n')

reject_url = 'https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/reject.txt'

if __name__ == '__main__':
    reject = get_ad(reject_url)

还有一个 小火煎的GEOIP,CN,DIRECT
貌似数据库不对 你可以实验一下 还是推荐用https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

**Comment by skylark36** [comment]
非常感谢建议。

首先针对第一点，telegram的规则我是从[Loyalsoldier/surge-rules](https://github.com/Loyalsoldier/surge-rules)同步过来的，然后我用着也没问题。我大概看了下，官方给的这个[https://core.telegram.org/resources/cidr.txt](https://core.telegram.org/resources/cidr.txt)应该是[Loyalsoldier/surge-rules](https://github.com/Loyalsoldier/surge-rules)的子集，本着不重复造轮子的原则也就不改动了。

第二，cdn有延迟这点我是知道的，但是有时候我会在本地测试，用githubusercontent会很慢，或者直接访问不了。而12小时左右的延迟其实对我们日常使用不会有什么影响，我们的规则不需要实时性很高。

最后，我也知道GEOIP的数据库是不全的，这里使用自带的GEOIP是因为如果加上china_ip_list的话，规则太庞大了（包括后面我也生成了一个不带去广告的规则，也是出于这方面的考虑）。而且从工程角度来看，数据库不全不影响什么，顶多就是偶尔有几个网站走了PROXY。

最后的最后，我一开始写这个东西的时候，也是想要把所有东西都加进去，包括但不限于收集很多去广告的规则、cnip和direct、扩充proxy，想要尽善尽美。

但是仔细想想，我基础的需求就是：
1. 我想上Google的同时能用网易云解锁
2. 我想要一点基础的去广告功能（甚至这点我也可以舍弃，因为去广告有太多方法了）

为了完善而用十几万条这么冗杂的规则值得吗？而对于日常使用，lhie1大佬的规则已经足够。所以，我现在日常使用的规则也只是black-netease.conf或者merge-lhie1.conf。当然每个人的需求不一样，所以，我也在readme里写了自定义开发的流程。

再次感谢建议，有什么想法可以大家一起讨论，大家共同进步哈，希望能有所帮助。
