### ISSUE TITLE
大佬请教个技术 问题 

### ISSUE THREAD

**Issue by luoluodaduan** [xiangsanliu/Rules#6]
wifi = set()
    for url in wifi_urls:
        rules = set(get_wifi(url))
        wifi = wifi.union(rules)
    wifi = list(wifi)
    wifi.sort()
怎么才能实现 忽略大小写的去重 不胜感激

**Comment by skylark36** [comment]
我想了想好像没有什么现成的api，手动写一个吧，就是可能时间复杂度比较高。
